# ################################################################################
# # Contains a list of tests to be run
# ################################################################################
---
testsuite:
  -    
    #########################################################################
    ###                       TestSuite_HATI CONFIG                      ###
    #########################################################################
    name: TestSuite_HATI_Config
    tests:
      - name: HATI_Config_Settings
        dut_index: 0
    