name: Build Sphinx Documentation

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build docs from'
        required: true
        default: 'main'

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3. Show working directory and files
      - name: Show current directory
        run: |
          pwd
          ls -la

      # 4. Install dependencies from requirements.txt
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # 5. Build documentation
      - name: Build documentation
        run: |
          # Make repo root importable for Sphinx autodoc
          export PYTHONPATH="${PWD}:${PYTHONPATH}"
          sphinx-apidoc -o docs/api .
          sphinx-build -b html docs docs/_build/html

      # 6. Upload built HTML as artifact
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-html-docs
          path: docs/_build/html
