################################################################################
# Contains a list of tests to be run
################################################################################
---
testsuite:
    #########################################################################
    ###                       TestSuite_NBIOT_NetworkPerformance          ###
    #########################################################################
  -
    name: TestSuite_NBIOT_NetworkPerformance
    tests:
      - name: NBIOT_NBDiag_AllECL
        dut_index: 0
        test_parameters:
          start_time_utc: "2024-05-16T00:00:00"
          end_time_utc: "2024-06-28T00:00:00"
          max_message_count: 500

      - name: NBIOT_NBDiag_AllNetPerf
        dut_index: 1
        test_parameters:
          start_time_utc: "2024-05-16T00:00:00"
          end_time_utc: "2024-06-28T00:00:00"
          max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 2
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 3
      #   test_parameters:
      #     # start_time_utc: "2024-05-16T00:00:00"   removing
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 4
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 5
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 6
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 7
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 8
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 9
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 10
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 11
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 12
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 13
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 14
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 15
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 16
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 17
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 18
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 19
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 20
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500
      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 21
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 22
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 23
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 24
      #   test_parameters:
      #     # start_time_utc: "2024-05-16T00:00:00"
      #     start_time_utc: "2024-06-28T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 25
      #   test_parameters:
      #     start_time_utc: "2024-05-24T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 26
      #   test_parameters:
      #     start_time_utc: "2024-05-30T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 27
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 28
      #   test_parameters:
      #     start_time_utc: "2024-05-17T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 29
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 30
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 31
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 32
      #   test_parameters:
      #     start_time_utc: "2024-05-24T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 33
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 34
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 35
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 36
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 37
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 38
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 39
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 40
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 41
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 42
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 43
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 44
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 45
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 46
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 47
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 48
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 49
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500

      # - name: NBIOT_NBDiag_AllNetPerf
      #   dut_index: 50
      #   test_parameters:
      #     start_time_utc: "2024-05-16T00:00:00"
      #     end_time_utc: "2024-06-28T00:00:00"
      #     max_message_count: 500
